In [1]:
import pandas as pd

In [2]:
import pandas as pd

customer_data = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5, 6, 7, 8],
    "customer_name": ["  john smith", "AMINA YUSUF ", "Li Chen", "maria lopez", "DAVID BROWN", "sara ahmed", "Tom Wilson ", "nina patel"],
    "monthly_fee": [49, 99, 29, 149, 99, 49, 199, 29],
    "months_active": [6, 18, 3, 24, 10, 2, 30, 4],
    "support_tickets": [1, 4, 0, 2, 5, 3, 1, 6],
    "days_since_login": [8, 35, 4, 12, 60, 45, 3, 75],
    "payment_status": ["Paid", "Paid", "Paid", "Overdue", "Overdue", "Paid", "Paid", "Overdue"]
})

customer_data

,customer_id,customer_name,monthly_fee,months_active,support_tickets,days_since_login,payment_status
0,1,john smith,49,6,1,8,Paid
1,2,AMINA YUSUF,99,18,4,35,Paid
2,3,Li Chen,29,3,0,4,Paid
3,4,maria lopez,149,24,2,12,Overdue
4,5,DAVID BROWN,99,10,5,60,Overdue
5,6,sara ahmed,49,2,3,45,Paid
6,7,Tom Wilson,199,30,1,3,Paid
7,8,nina patel,29,4,6,75,Overdue

In [6]:
def clean_customer_name(name):
    return name.strip().title()

clean_customer_name("  john smith")   # 'John Smith'

'John Smith'

In [23]:
def calculate_customer_value(monthly_fee, months_active):
    return monthly_fee * months_active

calculate_customer_value(99, 18)   # 1782

1782

In [7]:
def classify_customer_value(customer_value):
    if customer_value >= 2000:
        return "Premium"
    elif customer_value >= 750:
        return "Standard"
    else:
        return "Basic"

print(classify_customer_value(2500))   # Premium
print(classify_customer_value(1000))   # Standard
print(classify_customer_value(300))    # Basic

Premium
Standard
Basic

In [15]:
def calculate_risk_score(support_tickets, days_since_login, payment_status):
    score = 0

    if support_tickets >= 5:
        score += 2
    elif support_tickets >= 3:      # 3 to 4
        score += 1

    if days_since_login > 60:
        score += 2
    elif days_since_login >= 30:    # 30 to 60
        score += 1

    if payment_status == "Overdue":
        score += 2

    return score

In [10]:
# Test cases
print(calculate_risk_score(6, 75, "Overdue"))   # 2+2+2 = 6
print(calculate_risk_score(4, 35, "Paid"))       # 1+1+0 = 2
print(calculate_risk_score(1, 8,  "Paid"))       # 0+0+0 = 0
print(calculate_risk_score(5, 60, "Overdue"))    # 2+1+2 = 5  (60 is "30 to 60", not >60)

6
2
0
5

In [16]:
def classify_churn_risk(risk_score):
    if risk_score >= 5:
        return "High Risk"
    elif risk_score >= 3:           # 3 to 4
        return "Medium Risk"
    else:                           # 0 to 2
        return "Low Risk"

In [19]:
# Test churn risk classification
print(classify_churn_risk(6))   # High Risk
print(classify_churn_risk(4))   # Medium Risk
print(classify_churn_risk(2))   # Low Risk

High Risk
Medium Risk
Low Risk

In [24]:
def clean_customer_name(name):
    return name.strip().title()

def calculate_customer_value(monthly_fee, months_active):
    return monthly_fee * months_active

def classify_customer_value(customer_value):
    if customer_value >= 2000:
        return "Premium"
    elif customer_value >= 750:
        return "Standard"
    else:
        return "Basic"

def calculate_risk_score(support_tickets, days_since_login, payment_status):
    score = 0
    if support_tickets >= 5:
        score += 2
    elif support_tickets >= 3:
        score += 1
    if days_since_login > 60:
        score += 2
    elif days_since_login >= 30:
        score += 1
    if payment_status == "Overdue":
        score += 2
    return score

def classify_churn_risk(risk_score):
    if risk_score >= 5:
        return "High Risk"
    elif risk_score >= 3:
        return "Medium Risk"
    else:
        return "Low Risk"

print("All 5 helper functions defined.")

All 5 helper functions defined.

In [25]:
def prepare_customer_retention_data(df):
    df = df.copy()

    df["customer_name"] = df["customer_name"].apply(clean_customer_name)

    df["customer_value"] = df.apply(
        lambda r: calculate_customer_value(r["monthly_fee"], r["months_active"]), axis=1)

    df["value_segment"] = df["customer_value"].apply(classify_customer_value)

    df["risk_score"] = df.apply(
        lambda r: calculate_risk_score(
            r["support_tickets"], r["days_since_login"], r["payment_status"]), axis=1)

    df["churn_risk"] = df["risk_score"].apply(classify_churn_risk)

    return df

prepared_data = prepare_customer_retention_data(customer_data)
prepared_data

,customer_id,customer_name,monthly_fee,months_active,support_tickets,days_since_login,payment_status,customer_value,value_segment,risk_score,churn_risk
0,1,John Smith,49,6,1,8,Paid,294,Basic,0,Low Risk
1,2,Amina Yusuf,99,18,4,35,Paid,1782,Standard,2,Low Risk
2,3,Li Chen,29,3,0,4,Paid,87,Basic,0,Low Risk
3,4,Maria Lopez,149,24,2,12,Overdue,3576,Premium,2,Low Risk
4,5,David Brown,99,10,5,60,Overdue,990,Standard,5,High Risk
5,6,Sara Ahmed,49,2,3,45,Paid,98,Basic,2,Low Risk
6,7,Tom Wilson,199,30,1,3,Paid,5970,Premium,0,Low Risk
7,8,Nina Patel,29,4,6,75,Overdue,116,Basic,6,High Risk

In [26]:
def get_high_risk_customers(df):
    columns = ["customer_id", "customer_name", "customer_value",
               "support_tickets", "days_since_login", "payment_status", "churn_risk"]
    return df[df["churn_risk"] == "High Risk"][columns]

get_high_risk_customers(prepared_data)

,customer_id,customer_name,customer_value,support_tickets,days_since_login,payment_status,churn_risk
4,5,David Brown,990,5,60,Overdue,High Risk
7,8,Nina Patel,116,6,75,Overdue,High Risk

In [27]:
def summarize_risk_by_segment(df):
    return (df.groupby(["value_segment", "churn_risk"])
              .size()
              .reset_index(name="customer_count"))

summarize_risk_by_segment(prepared_data)

  value_segment churn_risk  customer_count
0         Basic  High Risk               1
1         Basic   Low Risk               3
2       Premium   Low Risk               2
3      Standard  High Risk               1
4      Standard   Low Risk               1

In [28]:
def create_follow_up_message(row):
    return (f"Contact {row['customer_name']}: {row['churn_risk']}. "
            f"Review account value of ${row['customer_value']}.")

# Apply to every customer
prepared_data.apply(create_follow_up_message, axis=1).tolist()

['Contact John Smith: Low Risk. Review account value of $294.',
 'Contact Amina Yusuf: Low Risk. Review account value of $1782.',
 'Contact Li Chen: Low Risk. Review account value of $87.',
 'Contact Maria Lopez: Low Risk. Review account value of $3576.',
 'Contact David Brown: High Risk. Review account value of $990.',
 'Contact Sara Ahmed: Low Risk. Review account value of $98.',
 'Contact Tom Wilson: Low Risk. Review account value of $5970.',
 'Contact Nina Patel: High Risk. Review account value of $116.']

In [31]:
print("HIGH RISK CUSTOMERS")
print(get_high_risk_customers(prepared_data)[["customer_name", "customer_value", "churn_risk"]])

print("\nRISK BY SEGMENT")
print(summarize_risk_by_segment(prepared_data))

HIGH RISK CUSTOMERS
  customer_name  customer_value churn_risk
4   David Brown             990  High Risk
7    Nina Patel             116  High Risk

RISK BY SEGMENT
  value_segment churn_risk  customer_count
0         Basic  High Risk               1
1         Basic   Low Risk               3
2       Premium   Low Risk               2
3      Standard  High Risk               1
4      Standard   Low Risk               1

In [ ]:
which customers should be contacted first?

In [ ]:
David Brown ($990) and Nina Patel ($116)

In [ ]:
Are any high-value customers at risk?

In [ ]:
No high-value

In [ ]:
What action should the company take?

In [ ]:
Contact both High Risk customers within 48 hours, starting with David Brown.in addition to that;Resolve their outstanding support tickets and clear overdue payments with a flexible plan.